eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka,http://localhost:8012/eureka,http://localhost:8013/eureka
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: words
words: NOT APPLICABLE

---
spring:
  profiles: word1
words: Pies, Kot

---
spring:
  profiles: word2
words: szczeka, miauczy